name: CI-CD Pipeline

     on:
  push:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Download Repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4

        with:
          node-version: 24

      - name: Install HTML Checker
        run: npm install -g htmlhint

      - name: Check HTML
        run: htmlhint index.html


  deploy:

    needs: test

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Download Repository
        uses: actions/checkout@v4
      - name:  show currint folder
        run: |
          pwd
          ls -la
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Website
        uses: actions/upload-pages-artifact@v3

        with:
          path: ./

      - name: Deploy Website
        id: deployment
        uses: actions/deploy-pages@v4
